-- Create the 'posts' table
create table public.posts (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  image_path text,
  caption text,
  hashtags text,
  internal_notes text,
  platforms text, -- JSON string or comma-separated
  platform_settings text, -- JSON string
  scheduled_time timestamp with time zone,
  status text default 'Pending'::text,
  is_recurring boolean default false,
  recurrence_frequency text,
  recurrence_end_date timestamp with time zone,
  source_mode text default 'Manual'::text
);

-- Enable Row Level Security (RLS) - Optional for internal tool but good practice
alter table public.posts enable row level security;

-- Create policy to allow all access (since this is an internal tool or we use service role)
-- For simplicity, if you are using 'anon' key from client, you need this.
-- If using 'service_role' from server, this isn't strictly needed but good to have.
create policy "Enable all access for all users"
on public.posts
for all
using (true)
with check (true);

-- Create Filter Bucket if it doesn't exist (You usually do this in UI)
insert into storage.buckets (id, name, public) 
values ('posts', 'posts', true)
on conflict (id) do nothing;

-- Storage Policy to allow public uploads (since we upload from server with service key technically we are fine, but for safety)
create policy "Public Access"
on storage.objects for all
using ( bucket_id = 'posts' )
with check ( bucket_id = 'posts' );
